-- Create database and schemas for RevSense AI project
-- Co-authored with CoCo
CREATE DATABASE IF NOT EXISTS REVSENSE_AI;

CREATE SCHEMA IF NOT EXISTS REVSENSE_AI.RAW;
CREATE SCHEMA IF NOT EXISTS REVSENSE_AI.STAGING;
CREATE SCHEMA IF NOT EXISTS REVSENSE_AI.MARTS;

CREATE WAREHOUSE IF NOT EXISTS REVSENSE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;